/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
        colors: {
            "surface-container-low": "#f6f4eb",
            "on-secondary": "#ffffff",
            "inverse-primary": "#c8c5ca",
            "on-tertiary-fixed": "#3f0300",
            "surface-variant": "#e4e2db",
            "tertiary-fixed": "#ffdad3",
            "on-tertiary-container": "#de5841",
            "error-container": "#ffdad6",
            "on-secondary-fixed-variant": "#5e4100",
            "on-secondary-fixed": "#271900",
            "on-primary-fixed-variant": "#47464a",
            "error": "#ba1a1a",
            "on-primary-container": "#858387",
            "surface-bright": "#fcf9f1",
            "secondary-container": "#fdd185",
            "surface": "#fcf9f1",
            "on-tertiary": "#ffffff",
            "background": "#fcf9f1",
            "surface-container-highest": "#e4e2db",
            "on-error-container": "#93000a",
            "inverse-on-surface": "#f3f1e9",
            "surface-container": "#f0eee6",
            "on-background": "#1b1c17",
            "on-surface": "#1b1c17",
            "tertiary": "#000000",
            "secondary": "#795919",
            "on-secondary-container": "#785818",
            "on-error": "#ffffff",
            "primary": "#000000",
            "inverse-surface": "#30312c",
            "primary-fixed-dim": "#c8c5ca",
            "secondary-fixed-dim": "#ebc076",
            "primary-container": "#1b1b1e",
            "on-primary": "#ffffff",
            "outline-variant": "#c8c5cb",
            "primary-fixed": "#e4e1e6",
            "secondary-fixed": "#ffdea9",
            "on-tertiary-fixed-variant": "#8a1b0b",
            "outline": "#78767b",
            "tertiary-container": "#3f0300",
            "surface-container-high": "#eae8e0",
            "on-surface-variant": "#47464b",
            "tertiary-fixed-dim": "#ffb4a6",
            "surface-dim": "#dcdad2",
        },
        spacing: {
            "margin-desktop": "32px",
            "gutter": "16px",
            "margin-mobile": "16px",
        },
        boxShadow: {
            "elevation-1": "0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)",
            "elevation-3": "0px 1px 3px 0px rgba(0, 0, 0, 0.3), 0px 4px 8px 3px rgba(0, 0, 0, 0.15)",
            "elevation-5": "0px 4px 4px 0px rgba(0, 0, 0, 0.3), 0px 8px 12px 6px rgba(0, 0, 0, 0.15)",
            "elevation-2": "0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)",
            "elevation-4": "0px 2px 3px 0px rgba(0, 0, 0, 0.3), 0px 6px 10px 4px rgba(0, 0, 0, 0.15)",
        },
        fontFamily: {
            "label-sm": "IBM Plex Mono",
            "body-lg": "IBM Plex Sans",
            "display-lg": "IBM Plex Mono",
            "title-sm": "IBM Plex Sans",
            "label-md": "IBM Plex Mono",
            "headline-sm": "IBM Plex Mono",
            "display-md": "IBM Plex Mono",
            "title-lg": "IBM Plex Sans",
            "headline-md": "IBM Plex Mono",
            "title-md": "IBM Plex Sans",
            "display-sm": "IBM Plex Mono",
            "body-sm": "IBM Plex Sans",
            "label-lg": "IBM Plex Mono",
            "headline-lg": "IBM Plex Mono",
            "body-md": "IBM Plex Sans",
        },
        fontSize: {
            "label-sm": "11px",
            "body-lg": "16px",
            "display-lg": "57px",
            "title-sm": "14px",
            "label-md": "12px",
            "headline-sm": "24px",
            "display-md": "45px",
            "title-lg": "22px",
            "headline-md": "28px",
            "title-md": "16px",
            "display-sm": "36px",
            "body-sm": "12px",
            "label-lg": "14px",
            "headline-lg": "32px",
            "body-md": "14px",
        },
        fontWeight: {
            "label-sm": "500",
            "body-lg": "400",
            "display-lg": "400",
            "title-sm": "500",
            "label-md": "500",
            "headline-sm": "400",
            "display-md": "400",
            "title-lg": "400",
            "headline-md": "400",
            "title-md": "500",
            "display-sm": "400",
            "body-sm": "400",
            "label-lg": "500",
            "headline-lg": "400",
            "body-md": "400",
        },
        lineHeight: {
            "label-sm": "16px",
            "body-lg": "24px",
            "display-lg": "64px",
            "title-sm": "20px",
            "label-md": "16px",
            "headline-sm": "32px",
            "display-md": "52px",
            "title-lg": "28px",
            "headline-md": "36px",
            "title-md": "24px",
            "display-sm": "44px",
            "body-sm": "16px",
            "label-lg": "20px",
            "headline-lg": "40px",
            "body-md": "20px",
        },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
